spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_test
    username: root
    password: mengchen0705
  session:
    # 关闭session管理
    store-type: none

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss