package test.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table branch
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Branch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.branch_id
     *
     * @mbg.generated
     */
    private Integer branchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.title_branch
     *
     * @mbg.generated
     */
    private String titleBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.is_lock
     *
     * @mbg.generated
     */
    private Integer isLock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.is_public
     *
     * @mbg.generated
     */
    private Integer isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.like_num
     *
     * @mbg.generated
     */
    private Integer likeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.dislike_num
     *
     * @mbg.generated
     */
    private Integer dislikeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.layer
     *
     * @mbg.generated
     */
    private Integer layer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.words
     *
     * @mbg.generated
     */
    private Integer words;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.branch_num
     *
     * @mbg.generated
     */
    private Integer branchNum;

    /**
     * Database Column Remarks:
     *   评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.comment_num
     *
     * @mbg.generated
     */
    private Integer commentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column branch.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.branch_id
     *
     * @return the value of branch.branch_id
     *
     * @mbg.generated
     */
    public Integer getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.branch_id
     *
     * @param branchId the value for branch.branch_id
     *
     * @mbg.generated
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.parent_id
     *
     * @return the value of branch.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.parent_id
     *
     * @param parentId the value for branch.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.book_id
     *
     * @return the value of branch.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.book_id
     *
     * @param bookId the value for branch.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.title_branch
     *
     * @return the value of branch.title_branch
     *
     * @mbg.generated
     */
    public String getTitleBranch() {
        return titleBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.title_branch
     *
     * @param titleBranch the value for branch.title_branch
     *
     * @mbg.generated
     */
    public void setTitleBranch(String titleBranch) {
        this.titleBranch = titleBranch == null ? null : titleBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.summary
     *
     * @return the value of branch.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.summary
     *
     * @param summary the value for branch.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.create_by
     *
     * @return the value of branch.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.create_by
     *
     * @param createBy the value for branch.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.create_time
     *
     * @return the value of branch.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.create_time
     *
     * @param createTime the value for branch.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.update_time
     *
     * @return the value of branch.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.update_time
     *
     * @param updateTime the value for branch.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.is_lock
     *
     * @return the value of branch.is_lock
     *
     * @mbg.generated
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.is_lock
     *
     * @param isLock the value for branch.is_lock
     *
     * @mbg.generated
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.is_public
     *
     * @return the value of branch.is_public
     *
     * @mbg.generated
     */
    public Integer getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.is_public
     *
     * @param isPublic the value for branch.is_public
     *
     * @mbg.generated
     */
    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.like_num
     *
     * @return the value of branch.like_num
     *
     * @mbg.generated
     */
    public Integer getLikeNum() {
        return likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.like_num
     *
     * @param likeNum the value for branch.like_num
     *
     * @mbg.generated
     */
    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.dislike_num
     *
     * @return the value of branch.dislike_num
     *
     * @mbg.generated
     */
    public Integer getDislikeNum() {
        return dislikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.dislike_num
     *
     * @param dislikeNum the value for branch.dislike_num
     *
     * @mbg.generated
     */
    public void setDislikeNum(Integer dislikeNum) {
        this.dislikeNum = dislikeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.layer
     *
     * @return the value of branch.layer
     *
     * @mbg.generated
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.layer
     *
     * @param layer the value for branch.layer
     *
     * @mbg.generated
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.words
     *
     * @return the value of branch.words
     *
     * @mbg.generated
     */
    public Integer getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.words
     *
     * @param words the value for branch.words
     *
     * @mbg.generated
     */
    public void setWords(Integer words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.branch_num
     *
     * @return the value of branch.branch_num
     *
     * @mbg.generated
     */
    public Integer getBranchNum() {
        return branchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.branch_num
     *
     * @param branchNum the value for branch.branch_num
     *
     * @mbg.generated
     */
    public void setBranchNum(Integer branchNum) {
        this.branchNum = branchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.comment_num
     *
     * @return the value of branch.comment_num
     *
     * @mbg.generated
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.comment_num
     *
     * @param commentNum the value for branch.comment_num
     *
     * @mbg.generated
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.status
     *
     * @return the value of branch.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.status
     *
     * @param status the value for branch.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column branch.content
     *
     * @return the value of branch.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column branch.content
     *
     * @param content the value for branch.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}