spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: mengchen0705
  session:
    store-type: none
  security:
    user:
      name: woxin
      password: 123456